#   _    _ _ _     _          _____ _____
#  | |  | (_) |   (_)   /\   |  __ \_   _|
#  | |__| |_| |__  _   /  \  | |__) || |
#  |  __  | | '_ \| | / /\ \ |  ___/ | |
#  | |  | | | |_) | |/ ____ \| |    _| |_
#  |_|  |_|_|_.__/|_/_/    \_\_|   |_____|
#
# An alternative implement of Imjad API

debug: false # 是否开启Debug模式
version: 0.5.0 # 程序版本, 勿动

data:
  temp-expiry: 7 # 临时文件目录文件过期时间, 单位为天
  path: ./data # data目录所在位置

server:
  host: 127.0.0.1 # 监听主机
  port: 8080 # 端口
  gzip: true

  cors:
    origins:
      - "http://localhost.tiangolo.com"
      - "https://localhost.tiangolo.com"
      - "http://localhost"
      - "http://localhost:8080"
    credentials: true
    methods: ["*"]
    headers: ["*"]

  allowed-forward: null # Reference: https://stackoverflow.com/questions/63511413

log:
  level: INFO # 日志等级, 可选 [TRACE,DEBUG,INFO,WARNING,ERROR]
  format: > # 输出日志格式, 如果没有必要请不要修改
    <level>
    <v>{level:<8}</v>
    [{time:YYYY/MM/DD} {time:HH:mm:ss.SSS} <d>{module}:{name}:{line}</d>]</level>
    {message}

  sentry:
    enabled: false
    sample: 1
    dsn: ""
    pii: false
