# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint

on:
  push:
    paths:
      - "**.py"
      - "**.pyi"
      - ".github/workflows/lint.yml"
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Code

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Set up Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('poetry.lock') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          pip install poetry
          poetry export -f requirements.txt -o /tmp/requirements.txt --dev
          pip install -r /tmp/requirements.txt

      - name: Run Linters
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          auto_fix: true
          flake8: true
          flake8_args: "--config .flake8"
          mypy: true
          mypy_args: ". --config .mypy.ini"
          black: true
          commit_message: ":rotating_light: 自动进行代码格式化"
          git_email: noreply@github.com
