name: Generate Requirements

on:
  workflow_dispatch:

  push:
    paths:
      - poetry.lock
      - pyproject.toml
      - requirements.txt

jobs:
  generate:
    name: Generate Requirements
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Generate dependencies
        run: |
          pip install poetry
          poetry export -f requirements.txt -o requirements.txt
          sed -i '1s/^/'"# $(date -R)"'\n/' requirements.txt
          pip install -r requirements.txt

      - name: Push to repository
        run: |
          cat requirements.txt
          git config --global user.name github-action
          git config --global user.email noreply@github.com
          git add requirements.txt
          git commit -am ":pushpin: 更新requirements.txt"
          git push
